openapi: 3.0.3
info:
  title: Proxy Generator API
  version: __VERSION__  # Automatically populated by `scripts/calculate_version.py` at release-time
  description: |
    <div class="nhsd-m-emphasis-box nhsd-m-emphasis-box--emphasis nhsd-!t-margin-bottom-6" aria-label="Highlighted Information">
        <div class="nhsd-a-box nhsd-a-box--border-blue">
            <div class="nhsd-m-emphasis-box__image-box">
                <figure class="nhsd-a-image">
                    <picture class="nhsd-a-image__picture">
                        <img src="http://digital.nhs.uk/binaries/content/gallery/icons/info.svg?colour=231f20" alt="" style="object-fit:fill">
                    </picture>
                </figure>
            </div>
            <div class="nhsd-m-emphasis-box__content-box">
                <div data-uipath="website.contentblock.emphasis.content" class="nhsd-t-word-break"><p class="nhsd-t-body">This API is <a href="https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses">in production, beta but internal</a>, meaning the API is not currently available for integration by external third parties. If you want to use it, <a href="https://digital.nhs.uk/developer/help-and-support">contact us</a> and we'll look at making it available.</p></div>            
            </div>
        </div>
    </div>

    ## Overview
    Use this API to create and manage resources on NHS England's [API platform](https://digital.nhs.uk/services/api-platform).
    This API is intended for API producers [building healthcare APIs](https://digital.nhs.uk/services/api-platform/building-healthcare-apis).

    You can:
    * Register new API definitions
    * Publish API specifications
    * Manage containers and secrets
    * Use your OAS specification to manage API proxies, products and security patterns

    In the future, you will be able to:
    * Secure the connection to your target service (back end) with MTLS. (Currently only API Key security is supported.)
    * Manage preview and live versions of your API's specification

    ## Who can use this API
    This API is currently for internal NHS England use only.

    ## Related APIs
    Can/should we remove this section?

    ## API status and roadmap
    This API is in [production, beta but internal](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses), meaning:
    * we might make breaking changes, but only if we cannot avoid it, and we will give advance notice
    * it is only available for internal NHS England users

    ## Service level
    This API is a bronze service, meaning it is operational and supported only during business hours (8am to 6pm), Monday to Friday excluding bank holidays.
    For more details, see [service levels](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#service-levels).

    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#basic-rest-apis).

    ## Network access
    This API is available on the internet and, indirectly, on the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).
    For more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).

    ## Security and authorisation
    Todo

    ## Environments and testing

    | Environment       | Base URL                                                               |
    | ----------------- | ---------------------------------------------------------------------- |
    | Development       | `https://proxygen.ptl.api.platform.nhs.uk`                             |
    | Production        | `https://proxygen.prod.api.platform.nhs.uk`                            |


    ### Development environment
    Our development environment:
    * is for developers of the Proxygen service itself
    * is not intended for [integration testing](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing)

    ## Onboarding
    This API is for internal NHS England users only. There is no onboarding process for external parties.
    The 'Getting started as an API Producer' section of the API Management NHS England Platforms Confluence space provides instructions on how to engage with us and start using Proxygen.

    ## Errors
    We use standard HTTP status codes to show whether an API request succeeded or not. They are usually in the range:

    * 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action
    * 400 to 499 if it failed because of a client error by your application
    * 500 to 599 if it failed because of an error on our server

    Errors specific to each API are shown in the Endpoints section, under Response. See our [reference guide](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#http-status-codes) for more on errors.
  license:
    name: MIT
  contact:
    name: API Management Support
    email: api.management@nhs.net
    url: 'https://digital.nhs.uk/developer/help-and-support'
x-spec-publication:
  # operation-order:
  #   - group: Some group
  #     operations:
  #       - method: GET
  #         path: /apis
  try-this-api:
    disabled: true
servers:
  - url: 'https://internal-dev.api.service.nhs.uk/proxygen-specification'
    description: Dummy environment. Required to appease Proxygen's OAS Parser which requires server URLs of a particular format.
  # - url: 'https://proxygen.prod.api.platform.nhs.uk'
  #   description: Production environment.
  # - url: 'https://proxygen.ptl.api.platform.nhs.uk'
  #   description: Development environment.
paths:
  /apis:
    description: A description for the whole path
    get:
      summary: Get list of APIs deployed through proxygen.
      description: A description for the GET operation specifically
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: hello-world
              examples:
                Example 1:
                  value:
                    - hello-world
                    - personal-demographics
      operationId: get-apis
    post:
      summary: Create pre-requisite resources for your API.
      operationId: post-apis
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api'
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api'
  '/apis/{api_name}':
    parameters:
      - schema:
          type: string
          example: hello-world
        name: api_name
        in: path
        required: true
    get:
      summary: Get an APIs deployed resources (secrets and instances)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/resource'
              examples:
                Example 1:
                  value:
                    - type: instance
                      environment: internal-dev
                      name: hello-world-test-123
                    - type: secret
                      environment: internal-dev
                      name: my-secret
      operationId: get-apis-api_name
    put:
      summary: Update pre-requisite resources for your API.
      operationId: put-apis-api_name
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api'
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPException'
              examples:
                Example 1:
                  value:
                    detail: Path parameter api_name='hello-world' does match request body 'something-else'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Api'
    delete:
      summary: Delete the pre-requisite resources for an API with no deployed resources
      operationId: delete-apis-api_name
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Api'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPException'
              examples:
                Example 1:
                  value:
                    detail: Cannot delete API with deployed resources.
  '/apis/{api_name}/docker-token':
    parameters:
      - schema:
          type: string
        name: api_name
        in: path
        required: true
    get:
      summary: Get an access token for our ECR
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: string
                  password:
                    type: string
                  registry:
                    type: string
                  expiresAt:
                    type: string
                    format: date-time
              examples:
                Example 1:
                  value:
                    user: AWS
                    password: '**********************'
                    registry: 'https://958002497996.dkr.ecr.eu-west-2.amazonaws.com'
                    expiresAt: '2022-10-26T02:05:39.540000+01:00'
      operationId: get-apis-api_name-docker-token
  '/apis/{api_name}/spec':
    parameters:
      - schema:
          type: string
        name: api_name
        in: path
        required: true
    get:
      summary: Get an API's spec
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaasOpenAPI'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPException'
              examples:
                Example 1:
                  value:
                    detail: Not found
      operationId: get-apis-api_name-spec
      requestBody:
        content: {}
    put:
      summary: Create or replace an API's spec
      operationId: put-apis-api_name-spec
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaasOpenAPI'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaasOpenAPI'
    delete:
      summary: Delete an API's spec
      operationId: delete-apis-api_name-spec
      responses:
        '204':
          description: No Content
  '/apis/{api_name}/environments':
    parameters:
      - schema:
          type: string
        name: api_name
        in: path
        required: true
    get:
      summary: Get everything deployed in environments for an API
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/resource'
              examples:
                Example 1:
                  value:
                    - type: instance
                      environment: internal-dev
                      name: hello-world-example-123
                    - type: secret
                      environment: internal-dev
                      name: my-secret-name
      operationId: get-apis-api_name-environments
      parameters:
        - schema:
            type: string
            enum:
              - instance
              - secret
          in: query
          name: _type
  '/apis/{api_name}/environments/{environment}':
    parameters:
      - schema:
          type: string
        name: api_name
        in: path
        required: true
      - schema:
          type: string
        name: environment
        in: path
        required: true
    get:
      summary: Get an API's resources deployed to a specific environment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resource'
      operationId: get-apis-api_name-environments-environment
  '/apis/{api_name}/environments/{environment}/secrets':
    parameters:
      - schema:
          type: string
        name: api_name
        in: path
        required: true
      - schema:
          type: string
        name: environment
        in: path
        required: true
    get:
      summary: Get the secrets for an API in a specific environment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/resource'
              examples:
                Example 1:
                  value:
                    - type: secret
                      environment: internal-dev
                      name: my-secret
                    - type: secret
                      environment: internal-dev
                      name: another-secret
      operationId: get-apis-api_name-environments-environment-secrets
  '/apis/{api_name}/environments/{environment}/secrets/{secret_name}':
    parameters:
      - schema:
          type: string
        name: api_name
        in: path
        required: true
      - schema:
          type: string
        name: environment
        in: path
        required: true
      - schema:
          type: string
        name: secret_name
        in: path
        required: true
    put:
      summary: Create or update a secret or API key
      operationId: put-apis-api_name-environments-environment-secrets-secret_name
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecretDescription'
              examples:
                Example 1:
                  value:
                    name: my-secret
                    type: secret
                    last_modified: '2019-08-24T14:15:22Z'
                    environment: internal-dev
                    apikey: false
                    version_id: 9e94c502-ca41-4342-a7f7-af96b444512c
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPException'
              examples:
                Example 1:
                  value:
                    detail: Request body cannot be empty
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              minLength: 1
      parameters:
        - schema:
            type: string
            enum:
              - apikey
          in: query
          name: _type
    delete:
      summary: Delete a secret or API key
      operationId: delete-apis-api_name-environments-environment-secrets-secret_name
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecretDescription'
  '/apis/{api_name}/environments/{environment}/instances':
    parameters:
      - schema:
          type: string
        name: api_name
        in: path
        required: true
      - schema:
          type: string
        name: environment
        in: path
        required: true
    get:
      summary: Get an API's instances for a specific environment
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/resource'
              examples:
                Example 1:
                  value:
                    - type: instance
                      environment: internal-dev
                      name: hello-world-instance-1
                    - type: instance
                      environment: internal-dev
                      name: hello-world-instance-2
      operationId: get-apis-api_name-environments-environment-instances
    post:
      summary: Create an API instance in a specific environment
      operationId: post-apis-api_name-environments-environment-instances
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaasOpenAPI'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPException'
              examples:
                Example 1:
                  value:
                    detail: API hello-world already has an instance hello-world-123 in internal-dev
      description: The instance name to be created is determined by base path of the server url
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaasOpenAPI'
  '/apis/{api_name}/environments/{environment}/instances/{instance_name}':
    parameters:
      - schema:
          type: string
        name: api_name
        in: path
        required: true
      - schema:
          type: string
        name: environment
        in: path
        required: true
      - schema:
          type: string
        name: instance_name
        in: path
        required: true
    get:
      summary: Get a specific API instance
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaasOpenAPI'
      operationId: get-apis-api_name-environments-environment-instances-instance_name
    put:
      summary: Update or create an API instance
      operationId: put-apis-api_name-environments-environment-instances-instance_name
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaasOpenAPI'
      description: The instance name supplied in the path parameter must match the one derived from the server.url
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaasOpenAPI'
    delete:
      summary: Delete a specific API instance
      operationId: delete-apis-api_name-environments-environment-instances-instance_name
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPException'
              examples:
                Example 1:
                  value:
                    detail: No instance hello-world-123 in environment internal-dev
  /specs:
    get:
      summary: Get all specifications
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    spec_id:
                      type: string
                      example: hello-world
                    last_modified:
                      type: string
                      format: date-time
              examples:
                Example 1:
                  value:
                    - spec_id: hello-world
                      last_modified: '2019-08-24T14:15:22Z'
                    - spec_id: personal-demographics
                      last_modified: '2019-08-22T12:14:11Z'
      operationId: get-specs
  '/specs/{api_name}':
    parameters:
      - schema:
          type: string
        name: api_name
        in: path
        required: true
    get:
      summary: Get an API's specification
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaasOpenAPI'
      operationId: get-specs-api_name
components:
  schemas:
    Api:
      title: Api
      type: object
      properties:
        name:
          type: string
        api_registry_entry:
          type: boolean
          default: true
        keycloak:
          type: boolean
          default: true
        keycloak_client_jwks_resource_url:
          type: string
        docker_repositories:
          type: array
          uniqueItems: true
          description: "Defaults to one repository with the same name as the API name.\r\n\r\nNames must be the same as, or start with, the API name.\r\n\r\nSend an empty list to have no repositories."
          items:
            type: string
            example: hello-world
      required:
        - name
    HTTPException:
      title: HTTPException
      type: object
      properties:
        detail:
          type: string
    LITERAL_ENVS:
      title: LITERAL_ENVS
      enum:
        - internal-dev
        - internal-dev-sandbox
        - internal-qa
        - internal-qa-sandbox
        - ref
        - dev
        - int
        - sandbox
        - prod
      description: ''
    resource:
      title: resource
      type: object
      properties:
        type:
          enum:
            - instance
            - secret
        environment:
          $ref: '#/components/schemas/LITERAL_ENVS'
        name:
          type: string
      x-examples:
        Example 1:
          type: instance
          environment: internal-dev
          name: hello-world-test-123
        Example 2:
          type: secret
          environment: internal-dev
          name: my-secret-name
    SecretDescription:
      title: SecretDescription
      type: object
      properties:
        name:
          type: string
        type:
          enum:
            - secret
        last_modified:
          type: string
          format: date-time
        environment:
          $ref: '#/components/schemas/LITERAL_ENVS'
        apikey:
          type: boolean
        version_id:
          type: string
          format: uuid
      required:
        - name
        - type
        - last_modified
        - environment
        - apikey
        - version_id
    PaasOpenAPI:
      title: OAS v3.0.3 Specification with proxygen-specific constraints and extensions
      description: |
        # Todo
        Describe how this isn't a full specification and why
      type: object
      required:
        - openapi
        - info
        - servers
        - paths
      properties:
        openapi:
          type: string
          enum:
          - '3.0.3'
        info:
          type: object
        externalDocs:
          type: object
        servers:
          type: array
          minLength: 1
          items:
            type: object
            required:
              - url
            properties:
              url:
                type: string
                # regex from proxygen.models.paas_open_api.server.URL_REGEX
                pattern: '^https://(internal-dev.api|internal-dev-sandbox.api|internal-qa.api|internal-qa-sandbox.api|ref.api|dev.api|int.api|sandbox.api|api).service.nhs.uk/((([a-zA-Z0-9])+[-/]?)+([a-zA-Z0-9])+)$'
              description:
                type: string
              variables:
                type: object
        security:
          type: array
          items:
            $ref: '#/components/schemas/PaasSecurityRequirement'
        tags:
          type: array
        paths:
          type: object
          properties:
            '^\/':
              type: object
              description: Some (any) path
              properties:
                summary:
                  type: string
                description:
                  type: string
                servers:
                  type: array
                parameters:
                  type: array
                get:
                  $ref: '#/components/schemas/Operation'
                put:
                  $ref: '#/components/schemas/Operation'
                post:
                  $ref: '#/components/schemas/Operation'
                delete:
                  $ref: '#/components/schemas/Operation'
                options:
                  $ref: '#/components/schemas/Operation'
                head:
                  $ref: '#/components/schemas/Operation'
                patch:
                  $ref: '#/components/schemas/Operation'
                trace:
                  $ref: '#/components/schemas/Operation'
        components:
          type: object
        x-nhsd-apim:
          $ref: '#/components/schemas/XNhsdApim'
                
    Operation:
      type: object
      properties:
        tags:
          type: array
        summary:
          type: string
        description:
          type: string
        externalDocs:
          type: object
        operationId:
          type: string
        servers:
          type: array
        security:
          $ref: '#/components/schemas/PaasSecurityRequirement'
        deprecated:
          type: boolean
        responses:
          type: object
        parameters:
          type: object
    
    PaasSecurityRequirement:
      type: object
      allOf:
      - $ref: '#/components/schemas/_PaasSecurity'

    EmptyList:
      type: array
      maxItems: 0
      # items: {}  - not sure what this does but was put in by stoplight so preserving it in case I want to put it back
   
    _PaasSecurity:
      type: object
      title: _PaasSecurity
      description: Some description
      oneOf:
        - properties:
            app_level0:
              $ref: '#/components/schemas/EmptyList'
          additionalProperties: false
          required:
            - app_level0
        - properties:
            app_level3:
              $ref: '#/components/schemas/EmptyList'
          additionalProperties: false
          required:
            - app_level3
        - properties:
            nhs_login_p0:
              $ref: '#/components/schemas/EmptyList'
          additionalProperties: false
          required:
            - nhs_login_p0
        - properties:
            nhs_login_p5:
              $ref: '#/components/schemas/EmptyList'
          additionalProperties: false
          required:
            - nhs_login_p5
        - properties:
            nhs_login_p9:
              $ref: '#/components/schemas/EmptyList'
          additionalProperties: false
          required:
            - nhs_login_p9
        - properties:
            nhs_cis2_aal1:
              $ref: '#/components/schemas/EmptyList'
          additionalProperties: false
          required:
            - nhs_cis2_aal1
        - properties:
            nhs_cis2_aal3:
              $ref: '#/components/schemas/EmptyList'
          additionalProperties: false
          required:
            - nhs_cis2_aal3
      x-examples:
        Example 1:
          app_level0: []
    XNhsdApim:
      type: object
      properties:
        target:
          $ref: '#/components/schemas/Target'
        access:
          type: array
          items:
            $ref: '#/components/schemas/Access'
        ratelimiting:
          $ref: '#/components/schemas/RateLimiting'
        monitoring:
          type: boolean
          default: true
        temporary:
          type: boolean
          default: false
    Target:
      allOf:
        - $ref: '#/components/schemas/BaseTarget'
      oneOf:
      - $ref: '#/components/schemas/HostedTarget'
      - $ref: '#/components/schemas/ExternalTarget'
    BaseTarget:
      type: object
      properties:
        healthcheck:
          type: string
          pattern: "^/"
    Access:
      type: object
      required:
        - title
        - grants
      properties:
        title:
          type: string
        grants:
          $ref: '#/components/schemas/PaasSecurityAccess'
        visible:
          type: boolean
          default: true
    PaasSecurityAccess:
      type: object
      allOf:
      - $ref: '#/components/schemas/_PaasSecurity'
    HostedTarget:
      type: object
      required:
      - containers
      - type
      properties:
        type:
          type: string
          enum:
           - hosted
        containers:
          type: array
          minItems: 1
          maxItems: 5
          uniqueItems: True
          items:
            $ref: '#/components/schemas/Container'

    Container:
      type: object
      required:
      - name
      - image
      properties:
        name:
          type: string
        image:
          $ref: '#/components/schemas/Image'
        environment:
          description: Environment variables
          type: object
        primary:
          type: boolean

    Image:
      type: object
      required:
      - name
      - tag
      properties:
        name:
          type: string
        tag:
          type: string
    ExternalTarget:
      type: object
      required:
      - url
      - security
      - type
      properties:
        type:
          type: string
          enum:
           - external
        url:
          type: string
          format: uri
        security:
          $ref: '#/components/schemas/APIKeyBackendSecurity'
    
    APIKeyBackendSecurity:
      type: object
      required:
      - type
      - header
      - secret
      properties:
        header:
          type: string
        secret:
          type: string
        type:
          type: string
          enum:
            - 'apikey'

    RateLimiting:
      type: object
      properties:
        proxy:
          $ref: '#/components/schemas/RateLimit'
        app_default:
          $ref: '#/components/schemas/RateLimit'
    
    RateLimit:
      type: object
      required:
      - timeunit
      - limit
      properties:
        timeunit:
          type: string
          enum:
            - 'second'
            - 'minute'
            - 'hour'
        limit:
          type: integer
          minimum: 0



